i18nを使って英語/日本語対応にする
Saki-htr/fjord-books_app pull request #1
Opened 2021-03-20 01:22 UTC by Saki-htr

2021-03-23 03:39 UTC, komagata requested changes

2021-03-23 03:39 UTC, komagata commented on app/views/books/index.html.erb
> +<%= link_to t('button.new'), new_book_path %>
ファイル末尾に改行が無いようです。
エディターの設定で自動的に入るようにできるので試してみてください〜

2021-03-23 03:39 UTC, komagata commented on package.json
> +  "name": 'books_app',
JSONは仕様として`'`（シングルクォート）を使うはずだと思うのでそちらでお願いします〜

2021-03-23 08:40 UTC, Saki-htr commented on app/views/books/index.html.erb
> +<%= link_to t('button.new'), new_book_path %>
VScodeで自動的に末尾に改行が入るように設定しました。

2021-03-23 08:41 UTC, Saki-htr commented on package.json
> +  "name": 'books_app',
JSONの仕様がシングルクォートと知らなかったです。次回以降気をつけます！

2021-03-24 04:16 UTC, komagata requested changes

2021-03-24 04:16 UTC, komagata commented on package.json
> +  'name': 'books_app',
こちらまだシングルクォートになっているようです〜

2021-03-28 03:30 UTC, Saki-htr commented on package.json
> +  'name': 'books_app',
すみません、どのように修正すればよいか分かりません💦

最初、「JSONの仕様はシングルクオート」と仰っていたので、package.json内のコードをすべてシングルクオートに直してという意味だと思い、すべてシングルクオートに変えて再提出したのですが、
「まだシングルクォートになっている」というのは、どのような意味でしょうか?

2021-03-29 14:58 UTC, komagata commented on package.json
> +  'name': 'books_app',
大変申し訳ないです、僕が間違っていました。JSONはダブルクォートでした。
両方ダブルクォートしていただければと思います。

http://www.tohoho-web.com/ex/json.html

2021-03-30 09:23 UTC, Saki-htr commented on package.json
> +  'name': 'books_app',
ダブルクオートなんですね！
根拠資料までつけていただいてありがとうございます✨
修正しましたので、ご確認をお願いいたします。

2021-03-31 03:18 UTC, komagata approved these changes
お手数おかけしました。確認しました、OKですー🙆‍♂️

2021-04-19 09:52 UTC, merged