kaminariでページング処理の実装
Saki-htr/fjord-books_app pull request #2
Opened 2021-03-20 07:24 UTC by Saki-htr

2021-03-23 03:50 UTC, komagata requested changes

2021-03-23 03:50 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(5)
`5`がマジックナンバーになっているのでkaminariの機能か定数などで指定したいですね

2021-03-23 03:50 UTC, komagata commented on config/locales/translation_ja.yml
> +      last: 最後へ
ファイルの末尾に改行が無いようです。
エディターの設定で自動的に入るようにできるので試してみてください〜

2021-03-28 05:54 UTC, Saki-htr commented on app/controllers/books_controller.rb
> +    @books = Book.order(:id).page(params[:page]).per(5)
`.per`を使わずに、`model/book.rb`で`paginates_per`を使って個数を指定するように変更しました。

2021-03-29 14:55 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-19 09:52 UTC, merged