ユーザーフォロー課題
Saki-htr/fjord-books_app pull request #6
Opened 2021-05-09 11:22 UTC by Saki-htr

課題を作成しましたので、レビューをお願い致します。

2021-05-13 01:52 UTC, u1tnk requested changes

2021-05-13 01:52 UTC, u1tnk commented on app/models/relationship.rb
> +class Relationship < ApplicationRecord
Relationshipだと抽象的過ぎるのでフォロー関係を表す名前にしましょう

2021-05-13 01:52 UTC, u1tnk commented on app/models/user.rb
> +    relationship = self.relationships.find_by(following_id: other_user.id)
細かいですが `relationships.find_by(following_id: other_user.id)&.destroy`でも同様と思います。

2021-06-03 08:56 UTC, Saki-htr commented on app/models/relationship.rb
> +class Relationship < ApplicationRecord
friendshipに変更しました!

2021-06-03 09:05 UTC, Saki-htr commented on app/models/user.rb
> +    relationship = self.relationships.find_by(following_id: other_user.id)
すみません、`git reset --hard`を使ったことにより、ローカルとリモートでコミット履歴が異なってしまい、リモートのコミット履歴を不要と判断して`git push origin mu-user-follow`で上書きしてしまいました。
このため、レビューしていただいた元のコードが消えてしまいました。
こちらどのように対処致せばよろしいでしょうか。
お手数をおかけしてすみませんが、よろしくお願いいたします。

2021-06-03 14:46 UTC, u1tnk commented on app/models/user.rb
> +    relationship = self.relationships.find_by(following_id: other_user.id)
消えた流れは私がアドバイスしたので仕方無いですよ。

ソースは残ってないですが、私のコメントは見れてますよね？2個だけだったか時間空いたので覚えてないですが 😓 

rebase/resetはこういう事になるので色々大変という事が勉強になったと思うのでそれで良しです 💪 

明日もう一回見ますので少々お待ちください 🙏

2021-06-03 21:51 UTC, Saki-htr commented on app/models/user.rb
> +    relationship = self.relationships.find_by(following_id: other_user.id)
ありがとうございます😭
コメントは全部で2個です。
たしかにチーム開発でこのようにコミット履歴が上書きされてしまうと大変ですね...rebase/resetには気をつけます！

2021-06-04 02:22 UTC, u1tnk approved these changes
ちょっとした点しか問題無かったので大丈夫です 🙆‍♀️

2021-06-04 02:22 UTC, u1tnk commented on app/controllers/friendships_controller.rb
> +    current_user.follow(params[:follow_id])
ちょっと細かいんですが、せっかくuser取得してるし

`current_user.follow(user)`の方が分かりやすいかなと思いました。微差ですが。

2021-06-04 02:22 UTC, u1tnk commented on app/helpers/friendships_helper.rb
> +# frozen_string_literal: true
こういう自動作成されただけのファイルは消しちゃいましょう！
必要になったら作れば良いし、なんでも増え過ぎると見づらくなってしまいます。

2021-06-05 00:42 UTC, merged